title: Robert Smith
logo: "/assets/img/me2.png"
description: >
  This is my online portfolio to showcase data analytics projects.  
  Let's connect on [LinkedIn](https://www.linkedin.com/in/rs4l/)

  **Certifications**  
  • [Google Advanced Data Analytics](https://www.coursera.org/account/accomplishments/professional-cert/SC7N8MJQCVH3)  
  • [Microsoft Excel Specialist](https://www.credly.com/badges/7b7871ae-86bc-448b-96a3-753a405f55a1/linked_in_profile)

show_downloads: false
show_github_link: false
theme: jekyll-theme-minimal
