title: Robert Smith
logo: "/assets/img/me2.png"
description: >
  This is my online portfolio to showcase data analytics projects. 
  Connect with me on LinkedIn: linkedin.com/in/rs4l



show_downloads: false
show_github_link: false
theme: jekyll-theme-minimal
